#!/usr/bin/env python3
"""
AskLAQ2 Application Launcher
This file is auto-generated by the deployment script
"""

import os
import sys
import webbrowser
import threading
import time
from pathlib import Path

def open_browser():
    """Open web browser after server starts"""
    time.sleep(2)  # Wait for server to start
    webbrowser.open("http://localhost:7860")

def main():
    print("=" * 50)
    print("AskLAQ2 - Local Q&A System")
    print("=" * 50)
    print("Starting the application...")
    print("
The application will open in your default web browser.")
    print("You can also access it at: http://localhost:7860")
    print("
Press Ctrl+C to stop the application.")
    print("-" * 50)
    
    # Start the application
    import gradio_app
    
    # Open browser in a separate thread
    browser_thread = threading.Thread(target=open_browser)
    browser_thread.daemon = True
    browser_thread.start()
    
    # Launch Gradio app
    gradio_app.demo.launch(
        server_name="0.0.0.0",
        server_port=7860,
        show_error=True,
        quiet=True
    )

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("

Application stopped by user.")
        sys.exit(0)
    except Exception as e:
        print(f"Error starting application: {e}")
        input("Press Enter to exit...")
        sys.exit(1)
